# Generated by Django 4.2.1 on 2023-05-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_delete_carrito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='moderador',
            new_name='admin',
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
