# Generated by Django 4.2.1 on 2023-05-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_rename_moderador_producto_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
